version: '2'
services:
  web:
    build:
      context: .
    ports:
      - "9001:9001"
      - "35729:35729"
    volumes:
      - "/Users/connie.cheung/Documents/Projects/CHHS/repo:/home/node/koe"
    depends_on:
      - chhs-mongo-1
    environment:
      - MONGODB_URI=mongodb://chhs-mongo-1/chhs-db
      - MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN
  chhs-mongo-1:
    image: mongo
    ports:
      - 27017:27017